security:
  oauth2:
    client:
      clientId: licensing
      clientSecret: secret
    resource:
       userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  security:
    enabled: false
    
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG    
    
server:
  port: 8183
